# Check `patterns.yaml` for available patterns, 'null' for no-pattern
pattern: Pulsar

config:
  width: 600
  height: 600
  rows: 9  # overridden by pattern
  cols: 9  # overridden by pattern
  frame_rate: 5
  bg_color:
    - 0  # red: range [0, 1]
    - 0  # blue: range [0, 1]
    - 0  # green: range [0, 1]
    - 1  # alpha: range [0, 1]
  recording_abspath: ""
  cell_color_map:
    - # CellState.DEAD
      - 50  # red: range [0, 255]
      - 50  # green: range [0, 255]
      - 50  # blue: range [0, 255]
    - # CellState.ALIVE
      - 200  # red: range [0, 255]
      - 200  # green: range [0, 255]
      - 200  # blue: range [0, 255]
